language: node_js
node_js:
- '9'
cache:
  yarn: true
  directories:
  - node_modules
notifications:
  email: false
jobs:
  include:
  - stage: deploy
    if: branch = master
    before_deploy:
    - yarn add now --no-save
    - now rm demo --token $NOW_TOKEN --yes || true
    deploy:
      provider: script
      script:
      - now demo --public --token $NOW_TOKEN -A ./now.json
      skip_cleanup: true
    after_success:
    - yarn build && yarn travis-deploy-once "yarn semantic-release"
env:
  global:
    secure: o4PH1Uk4Wbx4UgbbUQ6Md+Qk3AoBDpzMD8bV+YLviBv8SqUmHLkVoiE41B8eZOaMfpC3m5qoivNNeMmi5dx644oPTyt2pGNA5Wp2b2j9slQ/VvwvG8ksD7wShj98hXCVF2ylOQ6CQt7RkQKVuulgELNKFiJTcTAkcDQLOtgc1VpIXo06CY8zRzSXHPhYOrOTcekjAoTYeCBaNHmZv8pRGq6ibwJZTUMXAlRTGlKCvIXNiqwc3nDE/pXDWR1MPsnOIgNwhW3chwBA5JyOSBEKpBe2OFv9pnGExYyFoZEiYPFikMOnCmHVebXN7NuS0TtGHDYkUs3Y0tmc2jrfcd8hwWxKI76RWkRsDBfzHeS1Cuo22q9yVhc61XtH9jyc4FuJ+3OoXRkpyZ4L3wgKGxr1hpzK1RbUUa2t8PNJ3OObfOAN2MFcHg3X0Kkpa0wrQ3cg0ZGH3i3AzO2Z5yyee8IOjpl7RYh2AA85iL8/7Bide6Jz8u2nI9KCO1bNbwfTOR9T+L+xd8m9m1eVDGCk+Kv4PVXBPDs40miGpHlk18Q7sNl1ceciE4Au/3pfySeOUMSR5MCvuus92k1ETdhZU1b/RUZ1/i+kWWLJUqUoJIUhUZFkTPjWhzKH5tji2CCOuyn73sx4FK5i5vyToQEErjsZd0vUiAB1MJa7HYDmv6vZBXM=
