language: node_js
node_js: lts/*
cache:
  yarn: true
  directories:
  - ~/.npm
  - node_modules
notifications:
  email: false
before_deploy:
- yarn install now --no-save
- now rm mi18n --token $NOW_TOKEN --yes || true
deploy:
- provider: script
  script: now --public --token $NOW_TOKEN
  skip_cleanup: true
  on:
    master: true
after_success:
  - test $TRAVIS_BRANCH = "master" &&
    yarn travis-deploy-once "yarn semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
env:
  global:
  - secure: Lz+tEVu3T/LTXICa/O58JLvV5ivUdrIPhzFHQbFeceymBOeZxA5+drjLRL1g3goTPnyxyaVpHqOyMPGk1YT27GdmgZIVNAsByYNDXr466gxxu7VMgZkDHKmxZhemgij7wuTzbxWZdmt/UFOgn3SzeTL0ep5hJ20DEl4p4vI9/xB1jckUQVAH5ZFaeOF5UvhV0jmNJR2Z9N0rYlfaUhJlC1N8hnPA4m05wVZO/RC3nIxYW1xXJJZtiHspRyQ0EFqvogFalzxj0nSFcsj0TbSEiWqPhCh7p0iQXrTt+/cgqrh9RXjX+jRAjNHWiW0VLlRxzG+rrANJkCZj9K5dWuOjn3nQz6bI8CH5AtrUweFus53UAPRRZnjIR0Ua3ybyn0Yadfm0YERXz+L2c6iefRhI5ran1I8QW/IAWpv2U1Z1AIVz2BCoXUQK1fU/qAwI2r+miuFQsW/fs8TK4rvHYq/+1Ct6XvoSh/Y6BivEciQN+9bNOF89FnwLyYC4Oo6p1GFGU/bnvtHLUYAPCJg5Yuy5faC/7RwRNWedxJDUkozkX9zfH9KSWWiI3Vi0dNq4Eze1FK90u5qr9RiUD+6P1rhc7nkLNLK9umkMtcEmZaMWFhRYf4PyDxcO5jnV6LzsDghb1IINiNHIYjQrUvcqbih1sS/qIzA1dStxuvYPiKF8DkQ=
  - secure: itCeMxRKCNa515z1zZJNSb+oXgrBeTvdSGAZ8KHTWonTGqE6EDMId/MCqAbwMdNH2L/iUFejVNAJCLz+CoeZ5JDy+vtFYpBTDcgL8+8CfhL+5yHLE/oBSLQrlhNt6istJXLvpBt3+CMyqi9/m2SIue6IkOTqsMmQw7mYjCitBrEzzyYXeQI5jJ/ud+36Ondb01EjeMTD8w9fceTrlIt+eszvpLhkNtAQ4M/e5vIwKwGNKaywCwIbIw3U8SW4sRxHHf9wIJG8rV583BW5ei2me0ym/2/0/RWyMfw0hjhvmnlxjZJdpC2/vEECYILnJpeWxUnLjw1QcEATEkX50LXRCw8vmsL0xbgwQr85VK++HbbiHOx5AzD49zgUo3XJszojnAws9ERnM0TUUl+SU+UN7mvLfcwYTbwCvwUrdEJCULfnB6CWrJXjxyTWALJOoQjcpeJKF/gc48ucj9qAjE8vs4Hgy2P1GKY7biilWMPAt2WwY6B/Y+Gu95sz1dHLCauehMIzarR9UGmGIbrRhrTOn1nzU9fp2+jXs2Y3KhiVPuhiEVPgj0iJ+/hUN5pmjIQj7MUTvRMphjO8tcZk+LJW8Vu+3Xo9VG3qm6b7pru+vn8esA/8kV6Eg8O02ygFRXUslZRGNKCejZMbI8ywJ7YRRTA6FGeNL9TlGGhXNwxTccM=
  - secure: Jm+tayJmdD3JfWxGiJfuBDCv+Pi3JgWQcoyOpad6JPelNEHwOc9eWu0c0wVFAL+ba31mvj01ew2vTN9tjrsDE53/ktTkD2KK1koWr2qrzUHZ9TaJZbhY+FgJaIz7Yo2yXaGR3x/j+bb0WDDWbOJR/jNKFwIKyQyR1prCHljFGpbdOO1Kb5M2LIsiRjqiUfpyWUAlhGODJuO/VCTnOngp0f71xLqle5Wmn9BFSG+nVN9O11ev8rBTj9H2cRPqHTPfoylEKbdQUash9riFvPCXLhTw0eFnC61JQFH7oxYFVtKxcawHrDzx+6nJVDBLyt55tTApKQqb/fZa2bf9vvINccnM1EPxu4eWY4SRc4wHHEhplLgXlPKaT+LlWlfP4Kiv19qdxe6FZMkENj2LQulrK1JJwShpnJFTuWLLUbmSeg3Ga7olTw7hQFzqbTjLvqKJ4TtyNatbbbacoqPiwzQx+10NMLtCQCZdCDCDK2JzkXsCOaD8G0ukWCDnEY4qTwdm06C6+f7PCZCLo6H2nOGUb60Yob/rEFzQWMZAVSb7G6jDkBlCgqG8tLqVWCdVWlw1iB4EWksbLOlkrB8oWKaoFlX1uFvgyWaw4WpAcVwno7yhCYzOTfLMqgOUyqBRKeYh4IUYDWpcvSuEnTRaz7waJml1b9Hdga0IuK7yy5iHQRM=
